### ISSUE TITLE
Nivo not loading

### ISSUE THREAD

**Issue by russianlife** [stevewithington/MuraNivo#10]
Steve

Plug in loaded into Mura fine, functioning fine, but no slideshow showing up. In debugging panel, I see error nivoslider is not a function.

Do I need to hard code a line somewhere to load the Nivo js function? Here is the page: 
http://www.russianlife.com/stories/online-archive/43-russian-patriots/

Thanks.

PR

**Comment by russianlife** [comment]
I got it to load by adding the script load command in the htmlhead.cfm template, but the styling is a bit funky, and choosing diff themes does not change the appearance. Just seems like the plug in is not loading the way it should?

**Comment by stevewithington** [comment]
@russianlife you shouldn't have to hard code anything for this, and the link you've supplied says "Content Off-Line" which means you've set the content item to not display. Without seeing the issue, it's hard to tell what's wrong.

**Comment by russianlife** [comment]
Steve:

Yes, I had to turn off display as the post was showing up in some Content Collections, even tho Navigation was off. Fixed those collections and now it is live again

http://www.russianlife.com/stories/online-archive/43-russian-patriots/

But this is with the hard coding in place in the main html-head template. Maybe I should pull that for you to have a look?

Very bizarre. Wonder if I have some sort of js conflict? But even hard coding the js in there, the styling is off.

**Comment by stevewithington** [comment]
@russianlife yeah, for some reason, none of the scripts and css appear to be loading for you. Maybe in one of your contentRenderer.cfc's you have `this.renderHTMLHead=false`?

**Comment by russianlife** [comment]
No, only place I find the renderhtmlhead string in the site is in the contentrenderer.cfc in the requirements folder and it reads

<cfset this.renderHTMLHead=true/>

Later in the same file there is this too:

<cffunction name="setRenderHTMLQueues" returntype="void" output="false">
<cfargument name="renderHTMLQueues">
	<cfset this.renderHTMLQueues=arguments.renderHTMLQueues />
</cffunction>

<cffunction name="getRenderHTMLQueues" returntype="string" output="false">
	<cfreturn this.renderHTMLQueues and this.renderHTMLHead />
</cffunction>

<cffunction name="setRenderHTMLHead" returntype="void" output="false" hint="This is deprecated.">
<cfargument name="renderHTMLHead">
	<cfset this.renderHTMLQueues=arguments.renderHTMLQueues />
</cffunction>

<cffunction name="getRenderHTMLHead" returntype="string" output="false" hint="This is deprecated.">
	<cfreturn this.renderHTMLQueues />
</cffunction>

**Comment by deeztek** [comment]
I had a hell of a time with the nivo plugin. Piece of advise, drop the NIVO plugin and implement bxslider in your MURA installation. Very simple to install and configure without the weird little issues that nobody seems to have the answers to. Additionally, it seems to be a LOT better in terms of responsiveness than NIVO . If you are interested, I have a how-to here:

https://forums.deeztek.com/viewtopic.php?f=29&t=47826

If you want to see BXslider in action under MURA, check it out here:

http://www.visionexperts.com/

Thanks

**Comment by stevewithington** [comment]
@russianlife I would check your Site contentRenderer.cfc (/{SiteID}/includes/contentRenderer.cfc) and your Theme contentRenderer.cfc (/{SiteID/includes/themes/{ThemeName}/contentRenderer.cfc) and see if either of those settings are being overridden somehow because it appears that your queues aren't being rendered for some reason.

**Comment by russianlife** [comment]
Hm. Best I can see nothing unusual. Just a few functions (2 custom feeds and the main page output function) in the former, and in the latter just the Bootstrap Carousel function.

I did see this line in the former
<cfset this.renderHTMLQueues=true/>
and it was commented out, as are a bunch of other cfsets. I uncommented it but that does not seem to make any difference.

**Comment by russianlife** [comment]
Thanks, Deeztek, but what I need is something more sophisticated, like MuraNivo, because I need to be dynamically pulling in elements like photo, title, description from collections.

For just plain slider like you mention, I have used flexslider before and that works well.

Actually what I really want to do is implement MuraNivo to replace the gallery view, which is extremely basic. But that’s another issue.

PR
