### ISSUE TITLE
Does not work with M7+CodeBlue

### ISSUE THREAD

**Issue by Cyrillvatomsky** [stevewithington/MuraNivo#11]
I have M7 and legacy CodeBlue and although NM installs, loads and loads indexes the slider itself does not work. Images are just stacked. Links work.

Does work with the canned bootstrap3 theme.

**Comment by Cyrillvatomsky** [comment]
Take it back:-) Does not work with CodeBlue or MB3 in my localhost environment but works on a Hostek shared hosting deployment with both themes.

**Comment by stevewithington** [comment]
@Cyrillvatomsky i need a bit more information than "it doesn't work" ... do you have any specific errors that you can provide? For example, please check your JS console, it sounds like the JS/CSS aren't loading properly in your local environment for some reason. Is this a fresh install of Mura 7? Sorry ... but more info is definitely needed here.

**Comment by Cyrillvatomsky** [comment]
Steve, It does work on a standard shared hosting at Hostek. It does not work on my localhost that has been giving me hard time recently... You are right, most likely the javascrip is not loading. Initially I thought the legacy CodeBlue was at fault. Should take more time testing before I report :-)
