### ISSUE TITLE
On the index.cfm there are Line Seperator characters and its causing a bug in Firefox

### ISSUE THREAD

**Issue by CharlieBrumbaugh** [stevewithington/MuraNivo#14]
I am getting an illegal character message in the console after using this plugin in Firefox and its cuased by line separator characters.

You can see the problem here 

![bugs](https://user-images.githubusercontent.com/12149031/46974242-bb34ef80-d080-11e8-842e-6d4ffba93f34.png)

They are on lines 73,74,75,89

**Comment by stevewithington** [comment]
Fixed. Thank you.
