### ISSUE TITLE
Setting Slide Size to "Custom" Width to AUTO and Height to AUTO generates 500 Error

### ISSUE THREAD

**Issue by deeztek** [stevewithington/MuraNivo#7]
500 Error
Division by zero is not possible
Code: 0
Type: 0
Column: 0
ID: ??
Line: 196
Raw Trace: content.file.processimgcfimage_cfc$cf.udfCall(/var/www/dev2.visionexperts.com/requirements/mura/content/file/processImgCfimage.cfc:196)
Template: /var/www/dev2.visionexperts.com/requirements/mura/content/file/processImgCfimage.cfc
Type: cfml

**Comment by stevewithington** [comment]
@deeztek yeah, i don't believe Mura allows both width and height to be "auto" anymore ... so you'll have to set one of them explicitly. i actually suggest using a predefined image size (found under Site Config > Edit Site > Images tab) and use your defined imagesize name instead. this will allow you to create custom crops for the images.
