### ISSUE TITLE
Unable to load content collection

### ISSUE THREAD

**Issue by deeztek** [stevewithington/MuraNivo#8]
when I try to load the plugin using the method below I get "Ooops! The Content Collection originally used for this slider has been deleted!" even though it's a valid local content index that I just created. 
# $.muraNivo.dspMuraNivo(

```
feed='carousel'
, theme='default'
, size='large'
, height='AUTO'
, width='AUTO'
, sliderid = '#LCase(Replace(CreateUUID(), '-', '', 'ALL'))#'
, effect = 'random'
, showcaption = true
, pausetime = '3'
```

)#

**Comment by stevewithington** [comment]
@deeztek Please check that your content collection is actually called `carousel` ... some systems are case-sensitive. So, I would double check that as well.

**Comment by deeztek** [comment]
I verified that the name is exactly the same. I even renamed the local content index but same result. The weird thing is that if I insert the slider in a particular page from the layout and objects it works but I can't get the width to fill the whole page. That's why I wanted to try the dsp method above.
